// Import Angular core components
import { Component, OnInit } from '@angular/core';

// Import services and models used for fetching and managing analytics data
import { AnalyticsService, Alert, ReorderRecommendation, CostAnalysis } from '../../services/analytics.service';
import { AuditLogService, AuditLog } from '../../services/audit-log.service';
import { SharedDataService } from '../../services/shared-data.service';
import { InventoryService } from '../../services/inventory.service';
import { DeliveryService } from '../../services/delivery.service';
import { StockRequestService } from '../../services/stock-request.service';
import { AuthService } from '../../services/auth.service';
import { PdfReportService } from '../../services/pdf-report.service';
import { NotificationService } from '../../services/notification.service';
import { Router } from '@angular/router';
// Import forkJoin to run multiple RxJS observables in parallel
import { forkJoin } from 'rxjs';

/**
 * AnalyticsDashboardComponent
 * 
 * Provides a comprehensive dashboard for tracking inventory alerts, 
 * AI-driven reorder recommendations, cost impact analysis, and system audit logs.
 */
@Component({
  selector: 'app-analytics-dashboard',
  templateUrl: './analytics-dashboard.component.html',
  styleUrls: ['./analytics-dashboard.component.css']
})
export class AnalyticsDashboardComponent implements OnInit {
  
  // ==========================================
  // Demo Data (Fallback Data for Demonstrations)
  // ==========================================
  
  // Dummy inventory array used if backend is unavailable
  public demoInventory: any[] = [
    { id: 1, product: { id: 1, sku: 'PROD001', name: 'Milk 1L', category: 'Dairy', unitPrice: 1047, reorderLevel: 50, minStockLevel: 20, perishable: true, active: true, createdAt: new Date(), updatedAt: new Date() }, quantity: 100, reorderLevel: 50, lastUpdated: new Date(), lowStockAlert: false, createdAt: new Date(), updatedAt: new Date() },
    { id: 2, product: { id: 2, sku: 'PROD002', name: 'Bread Loaf', category: 'Bakery', unitPrice: 697, reorderLevel: 40, minStockLevel: 15, perishable: true, active: true, createdAt: new Date(), updatedAt: new Date() }, quantity: 50, reorderLevel: 40, lastUpdated: new Date(), lowStockAlert: false, createdAt: new Date(), updatedAt: new Date() }
  ];
  
  // Dummy deliveries array
  public demoDeliveries: any[] = [
    { id: 1, trackingNumber: 'TRK-001', product: null, quantity: 100, status: 'DELIVERED', estimatedDelivery: new Date(), actualDelivery: new Date(), createdAt: new Date(), updatedAt: new Date() },
    { id: 2, trackingNumber: 'TRK-002', product: null, quantity: 50, status: 'IN_TRANSIT', estimatedDelivery: new Date(), createdAt: new Date(), updatedAt: new Date() }
  ];
  
  // Dummy stock requests array
  public demoRequests: any[] = [
    { id: 1, product: null, requestedQuantity: 100, status: 'APPROVED', requestDate: new Date(), approvalDate: new Date() },
    { id: 2, product: null, requestedQuantity: 50, status: 'PENDING', requestDate: new Date(), approvalDate: null }
  ];

  // ==========================================
  // Component State Properties
  // ==========================================
  
  alerts: Alert[] = [];                                      // Array of all system alerts generated by AnalyticsService
  criticalAlerts: Alert[] = [];                              // Array containing only 'CRITICAL' severity alerts
  reorderRecommendations: ReorderRecommendation[] = [];      // Array of AI-suggested reorder quantities
  costAnalysis: CostAnalysis | null = null;                  // Object holding financial impact data (stockouts, excess, etc.)
  recentAuditLogs: AuditLog[] = [];                          // Array of recent system actions/events
  
  selectedTab: 'alerts' | 'reorder' | 'costs' | 'audit' = 'alerts'; // Currently active tab in the UI (defaults to alerts)
  
  // Object keeping track of alert counts by severity level
  alertStats = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0
  };

  /**
   * Constructor: Inject required services for fetching data and showing notifications.
   */
  constructor(
    private analytics: AnalyticsService,
    private auditLog: AuditLogService,
    private sharedData: SharedDataService,
    private pdfReport: PdfReportService,
    private inventoryService: InventoryService,
    private deliveryService: DeliveryService,
    private stockRequestService: StockRequestService,
    private notifications: NotificationService,
    public auth: AuthService, // Public so template can check user roles
    private router: Router
  ) {}


  /**
   * Angular lifecycle hook called on initialization.
   * Sets up demo data, fetches real data from backend, and subscribes to real-time streams.
   */
  ngOnInit(): void {
    // 1. Populate demo arrays with rich mock data
    this.initializeHardcodedData();
    
    // 2. Fetch real data from backend APIs
    this.loadAnalytics();
    
    // 3. Subscribe to the alerts observable to get real-time updates when alerts are generated/acknowledged
    this.analytics.alerts$.subscribe(alerts => {
      this.alerts = alerts;
      this.calculateAlertStats(); // Recalculate badge numbers
    });
    
    // 4. Subscribe to the recommendations observable
    this.analytics.reorderRecommendations$.subscribe(recs => {
      this.reorderRecommendations = recs;
    });
    
    // 5. Load the 20 most recent audit logs
    this.recentAuditLogs = this.auditLog.getRecentLogs(20);
  }

  /**
   * Populates the component with comprehensive dummy data for fallback scenarios or demos.
   */
  initializeHardcodedData(): void {
    // Comprehensive demo inventory with LKR prices
    this.demoInventory = [
      { id: 1, product: { id: 1, sku: 'PROD001', name: 'Organic Whole Milk', category: 'Dairy', unitPrice: 899.00, reorderLevel: 50, minStockLevel: 30, perishable: true, active: true }, quantity: 150, reorderLevel: 50, lowStockAlert: false },
      { id: 2, product: { id: 2, sku: 'PROD002', name: 'White Bread Loaf', category: 'Bakery', unitPrice: 449.00, reorderLevel: 40, minStockLevel: 20, perishable: true, active: true }, quantity: 200, reorderLevel: 40, lowStockAlert: false },
      { id: 3, product: { id: 3, sku: 'PROD003', name: 'Premium Ground Coffee', category: 'Beverages', unitPrice: 2499.00, reorderLevel: 30, minStockLevel: 10, perishable: false, active: true }, quantity: 85, reorderLevel: 30, lowStockAlert: false },
      { id: 4, product: { id: 4, sku: 'PROD004', name: 'Cheddar Cheese Block', category: 'Dairy', unitPrice: 1199.00, reorderLevel: 25, minStockLevel: 8, perishable: true, active: true }, quantity: 18, reorderLevel: 25, lowStockAlert: true },
      { id: 5, product: { id: 5, sku: 'PROD005', name: 'Chicken Breast (1kg)', category: 'Meat', unitPrice: 1599.00, reorderLevel: 35, minStockLevel: 15, perishable: true, active: true }, quantity: 65, reorderLevel: 35, lowStockAlert: false },
      { id: 6, product: { id: 6, sku: 'PROD006', name: 'Eggs (Dozen)', category: 'Dairy', unitPrice: 599.00, reorderLevel: 45, minStockLevel: 20, perishable: true, active: true }, quantity: 320, reorderLevel: 45, lowStockAlert: false },
      { id: 7, product: { id: 7, sku: 'PROD007', name: 'Olive Oil 500ml', category: 'Cooking', unitPrice: 1899.00, reorderLevel: 20, minStockLevel: 8, perishable: false, active: true }, quantity: 12, reorderLevel: 20, lowStockAlert: true },
      { id: 8, product: { id: 8, sku: 'PROD008', name: 'Brown Rice 2kg', category: 'Grains', unitPrice: 749.00, reorderLevel: 30, minStockLevel: 12, perishable: false, active: true }, quantity: 95, reorderLevel: 30, lowStockAlert: false }
    ];
    
    // Comprehensive demo deliveries
    this.demoDeliveries = [
      { id: 1, trackingNumber: 'TRK-2026-001', product: this.demoInventory[0].product, quantity: 100, status: 'DELIVERED', estimatedDelivery: new Date('2026-02-03'), deliveredAt: new Date('2026-02-03') },
      { id: 2, trackingNumber: 'TRK-2026-002', product: this.demoInventory[2].product, quantity: 50, status: 'IN_TRANSIT', estimatedDelivery: new Date('2026-02-06') },
      { id: 3, trackingNumber: 'TRK-2026-003', product: this.demoInventory[7].product, quantity: 120, status: 'DELIVERED', estimatedDelivery: new Date('2026-02-02'), deliveredAt: new Date('2026-02-02') },
      { id: 4, trackingNumber: 'TRK-2026-004', product: this.demoInventory[5].product, quantity: 200, status: 'DISPATCHED', estimatedDelivery: new Date('2026-02-07') }
    ];
    
    // Comprehensive demo stock requests
    this.demoRequests = [
      { id: 1, product: this.demoInventory[0].product, requestedQuantity: 100, status: 'APPROVED', requestDate: new Date('2026-02-01'), approvalDate: new Date('2026-02-02') },
      { id: 2, product: this.demoInventory[2].product, requestedQuantity: 50, status: 'PENDING', requestDate: new Date('2026-02-04') },
      { id: 3, product: this.demoInventory[4].product, requestedQuantity: 75, status: 'PENDING', requestDate: new Date('2026-02-05') }
    ];
  }

  /**
   * Passes the fallback/demo data into the Analytics service to trigger calculations manually.
   */
  runAnalytics(): void {
    this.analytics.analyzeInventory(this.demoInventory, []);
    this.analytics.analyzeDeliveries(this.demoDeliveries);
    this.analytics.generateReorderRecommendations(this.demoInventory);
    this.costAnalysis = this.analytics.calculateCostAnalysis(this.demoInventory, this.demoDeliveries, this.demoRequests);
  }

  // Expose JavaScript Math object so it can be used in the HTML template (e.g., Math.round)
  Math = Math;

  /**
   * Fetches real inventory, delivery, and request data from the backend APIs concurrently.
   * Once all three complete, it feeds the data into the AnalyticsService to generate insights.
   */
  loadAnalytics(): void {
    // Determine context based on route
    let inventoryObs = this.inventoryService.getAllInventory();
    if (this.router.url.includes('/warehouse')) {
      inventoryObs = this.inventoryService.getWarehouseInventory(1);
    }

    // forkJoin executes all provided observables in parallel and emits once all complete
    forkJoin({
      inventory: inventoryObs,
      deliveries: this.deliveryService.getAllDeliveries(),
      requests: this.stockRequestService.getAllRequests()
    }).subscribe({
      next: ({ inventory, deliveries, requests }) => {
        
        // Helper function to extract array from various backend response wrapper formats
        const extractArray = (res: any) => {
          if (Array.isArray(res)) return res;
          if (res && typeof res === 'object' && Array.isArray(res.data)) return res.data;
          if (res && typeof res === 'object' && Array.isArray(res.content)) return res.content;
          return [];
        };

        // Extract clean arrays
        let invArray = extractArray(inventory);
        let delArray = extractArray(deliveries);
        let reqArray = extractArray(requests);

        // Fallback to demo data if API returns empty arrays (useful for initial empty databases)
        if (invArray.length === 0) invArray = this.demoInventory;
        if (delArray.length === 0) delArray = this.demoDeliveries;
        if (reqArray.length === 0) reqArray = this.demoRequests;

        // Feed arrays into AnalyticsService engines to generate alerts, recommendations, and costs
        this.analytics.analyzeInventory(invArray, []);
        this.analytics.analyzeDeliveries(delArray);
        this.analytics.generateReorderRecommendations(invArray);
        this.costAnalysis = this.analytics.calculateCostAnalysis(invArray, delArray, reqArray);
      },
      error: err => {
        // On error (e.g., backend down), fallback to generating analytics from hardcoded data
        console.error('Failed to load analytics data, falling back to local demo data', err);
        this.runAnalytics();
      }
    });
  }

  /**
   * Getter property: Returns only alerts that haven't been acknowledged yet.
   */
  get unacknowledgedAlerts(): Alert[] {
    return this.alerts.filter(a => !a.acknowledged);
  }

  /**
   * Marks a specific alert as acknowledged (dimming it in the UI).
   * @param alertId - ID of the alert to acknowledge
   */
  acknowledgeAlert(alertId: number): void {
    this.analytics.acknowledgeAlert(alertId);
  }

  /**
   * Clears (removes) all alerts that have been acknowledged from the view.
   */
  clearAcknowledged(): void {
    this.analytics.clearAcknowledgedAlerts();
  }

  /**
   * Creates a new Stock Request based on an AI Reorder Recommendation.
   * Sends the request to the backend.
   * @param rec - The specific ReorderRecommendation object to act upon
   */
  createStockRequest(rec: ReorderRecommendation): void {
    // Determine the current user's supermarket ID (default to 1)
    const user = this.auth.getCurrentUser();
    const supermarketId = user?.supermarketId || 1;

    // Build the request payload
    const newRequest = {
      supermarketId: supermarketId,
      warehouseId: 1, // Assume SL Warehouse (ID 1)
      productId: rec.productId,
      requestedQuantity: rec.recommendedQuantity,
      status: 'PENDING',
      priority: 'MEDIUM',
      notes: `Automated restock request based on AI reorder recommendation: ${rec.reasoning}`,
      requestedAt: new Date()
    };

    // Submit request via StockRequestService
    this.stockRequestService.createRequest(newRequest as any).subscribe({
      next: (res) => {
        this.notifications.success(`Stock request submitted for ${rec.productName}`);
        
        // Try to construct an enriched object to update the local SharedDataService immediately
        const created = res && (res as any).data ? (res as any).data : null;
        const enriched = {
          id: created?.id || Date.now(),
          requestNumber: created?.requestNumber || `REQ-${Date.now()}`,
          supermarket: { id: supermarketId, name: `Supermarket #${supermarketId}` },
          warehouse: { id: 1, name: 'SL Warehouse' },
          product: { id: rec.productId, name: rec.productName },
          requestedQuantity: rec.recommendedQuantity,
          status: 'PENDING',
          priority: 'MEDIUM',
          requestedBy: null,
          requestedAt: new Date()
        };
        // Update global state
        this.sharedData.addStockRequest(enriched);
        
        // Refresh analytics data so the recommendation is updated/removed
        this.loadAnalytics();
      },
      error: (err) => {
        this.notifications.error('Failed to submit restock request');
        console.error(err);
      }
    });
  }

  /**
   * Returns a CSS class string based on the severity level of an alert.
   * Used for styling alert cards (e.g., red for critical, yellow for medium).
   * @param severity - Severity level string
   */
  getSeverityClass(severity: string): string {
    const classes: any = {
      'CRITICAL': 'severity-critical',
      'HIGH': 'severity-high',
      'MEDIUM': 'severity-medium',
      'LOW': 'severity-low'
    };
    return classes[severity] || '';
  }

  /**
   * Returns an emoji icon based on the type of alert.
   * @param type - Alert type string
   */
  getAlertIcon(type: string): string {
    const icons: any = {
      'LOW_STOCK': '📉',
      'EXPIRING': '⏰',
      'DELAYED_DELIVERY': '🚨',
      'DEMAND_SPIKE': '📈',
      'COST_WARNING': '💰'
    };
    return icons[type] || '⚠️';
  }

  /**
   * Returns a CSS class string based on confidence score (0-100).
   * Used for styling the confidence badge colors.
   * @param confidence - Confidence score
   */
  getConfidenceClass(confidence: number): string {
    if (confidence >= 85) return 'confidence-high';   // Green
    if (confidence >= 70) return 'confidence-medium'; // Orange
    return 'confidence-low';                          // Red
  }

  /**
   * Helper to format a number into an LKR currency string with thousands separators.
   * @param value - Amount to format
   */
  formatCurrency(value: number): string {
    return 'LKR ' + value.toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,');
  }

  /**
   * Private helper method that recalculates the counts of alerts by severity.
   * Updates the alertStats object used in the UI badges.
   */
  private calculateAlertStats(): void {
    this.alertStats = {
      critical: this.alerts.filter(a => a.severity === 'CRITICAL').length,
      high: this.alerts.filter(a => a.severity === 'HIGH').length,
      medium: this.alerts.filter(a => a.severity === 'MEDIUM').length,
      low: this.alerts.filter(a => a.severity === 'LOW').length
    };
  }

  /**
   * Filters the Audit Logs list based on a search string query.
   * Filters on action, entity, user, and details.
   * @param query - Search term
   */
  searchAuditLogs(query: string): void {
    if (query.trim()) {
      // Use audit log service to search, then slice first 20 results
      this.recentAuditLogs = this.auditLog.searchLogs(query).slice(0, 20);
    } else {
      // If empty query, restore default 20 recent logs
      this.recentAuditLogs = this.auditLog.getRecentLogs(20);
    }
  }

  /**
   * Triggers generation and download of a PDF report summarizing all current analytics.
   * Delegates the actual PDF generation to the PdfReportService.
   */
  exportToPdf(): void {
    this.pdfReport.generateAnalyticsReport(
      this.alerts,
      this.reorderRecommendations,
      this.costAnalysis || { // Pass default empty object if cost analysis is null
        totalInventoryValue: 0,
        totalCostImpact: 0,
        excessInventoryCost: 0,
        stockoutCost: 0,
        deliveryDelayCost: 0,
        monthlyTrend: 0
      }
    );
  }
}
